# Copyright 2026 TEAM RelicFrog
# SPDX-License-Identifier: Apache-2.0
apiVersion: apps/v1
kind: Deployment
metadata:
  name: primes-zig
  namespace: primes-workshop
  labels:
    app: primes-zig
    lang: zig
    example: devbox-workshop
spec:
  replicas: 1
  selector:
    matchLabels:
      app: primes-zig
  template:
    metadata:
      labels:
        app: primes-zig
        lang: zig
    spec:
      containers:
        - name: primes-zig
          image: primes-zig:latest
          imagePullPolicy: Never
          resources:
            requests:
              cpu: "50m"
              memory: "32Mi"
            limits:
              cpu: "200m"
              memory: "64Mi"
